# Generated by Django 4.2.4 on 2023-08-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_refreshtokens_delete_tokenblacklistoutstandingtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refreshtokens',
            table='token_blacklist_outstandingtoken',
        ),
    ]
