# Generated by Django 4.2.4 on 2023-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_refreshtokens_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokensBlacklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
    ]
