# Generated by Django 4.2.3 on 2023-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_disabledtokens_delete_refreshtokensblacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disabledTokens',
        ),
        migrations.DeleteModel(
            name='RefreshTokens',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
